version: '3.8'
services:
  json2arkts:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        # 这里需要替换为自己的实际代理信息，或者注释掉
        PROXY: http://192.168.50.48:7890
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "0.0.0.0:7860:7860"